#!/bin/bash
#
# Generate build/config_autogen.h and build/config.mk from .config
#
# This translates Kconfig-style CONFIG_* names into the BIOS_CFG_*
# names expected by the BIOS source code.
#

set -e

CONFIG="${1:-.config}"
HEADER="${2:-build/config_autogen.h}"
MAKEFILE="${3:-build/config.mk}"

if [ ! -f "$CONFIG" ]; then
    echo "mkconfig.sh: $CONFIG not found" >&2
    exit 1
fi

mkdir -p "$(dirname "$HEADER")" "$(dirname "$MAKEFILE")"

. "$CONFIG"

# Kconfig writes '# CONFIG_FOO is not set' for disabled booleans.
# Bash sourcing treats them as comments, leaving the variable unset, which
# causes ${CONFIG_FOO:-y} defaults to silently re-enable the option.
# Explicitly set every "not set" variable to "n" so disabled booleans stay
# disabled while genuinely missing legacy keys can still fall back.
while IFS= read -r line; do
    case "$line" in
        '# CONFIG_'*' is not set')
            varname="${line#\# }"
            varname="${varname%% *}"
            eval "$varname=n"
            ;;
    esac
done < "$CONFIG"

# --- Helper: emit a #define ---
emit() {
    echo "#undef  $1"
    echo "#define $1 $2"
}

emit_str() {
    echo "#undef  $1"
    echo "#define $1 \"$2\""
}

bool_val() {
    if [ "$1" = "y" ]; then echo 1; else echo 0; fi
}

# Strip 0x prefix if present (Kconfig hex values include it)
strip_0x() {
    echo "${1#0x}"
}

# --- Floppy drive type mapping ---
floppy_type_macro() {
    case "$1" in
        180K) echo "BIOS_FLOPPY_TYPE_180K_525SD" ;;
        360K) echo "BIOS_FLOPPY_TYPE_360K_525DD" ;;
        720K) echo "BIOS_FLOPPY_TYPE_720K_35DD" ;;
        *)    echo "BIOS_FLOPPY_TYPE_NONE" ;;
    esac
}

TARGET=pc1640dd
MACHINE_SRC="src/machine/pc1640dd/machine_pc1640dd.c"
ROM_LAYOUT="pc1640dd"
ROM_ENTRY_SEGMENT="0xFC00"
ROM_IMAGE_SIZE="0x4000"
ROM_MACHINE_ID_BYTE="0xFE"
ROM_COMPAT_PATCH_ENABLED="y"
ROM_COMPAT_HOLE_OFFSET="0x3065"
ROM_COMPAT_HOLE_SIZE="5"
ROM_ROS_CHECKSUM_ENABLED="y"
EXECUTE_IN_PLACE="y"
RUNTIME_SEGMENT="$ROM_ENTRY_SEGMENT"
STACK_SEGMENT="0x0030"
STACK_OFFSET="0x0100"
HAS_PARADISE_PEGA1A="y"
HAS_AMSTRAD_MOUSE="y"
HAS_BATTERY_BACKED_RTC="y"
HAS_DMA_CONTROLLER="y"
VIDEO_OPTION_ROM_SCAN_START="0xC000"
VIDEO_OPTION_ROM_SCAN_END="0xC800"
OPTION_ROM_SCAN_START="0xC800"
OPTION_ROM_SCAN_END="0xF000"
POST_DMA_TEST_ENABLED="y"
POST_SYSTEM_STATUS_TEST_ENABLED="y"
POST_RTC_TEST_ENABLED="y"

POST_ROS_CHECKSUM_TEST_ENABLED="${CONFIG_POST_ROS_CHECKSUM_TEST_ENABLED-y}"
POST_VIDEO_MEMORY_TEST_ENABLED="${CONFIG_POST_VIDEO_MEMORY_TEST_ENABLED-y}"
POST_DMA_TEST_ENABLED="${CONFIG_POST_DMA_TEST_ENABLED-$POST_DMA_TEST_ENABLED}"
POST_TIMER_TEST_ENABLED="${CONFIG_POST_TIMER_TEST_ENABLED-y}"
POST_SYSTEM_STATUS_TEST_ENABLED="${CONFIG_POST_SYSTEM_STATUS_TEST_ENABLED-$POST_SYSTEM_STATUS_TEST_ENABLED}"
POST_RTC_TEST_ENABLED="${CONFIG_POST_RTC_TEST_ENABLED-$POST_RTC_TEST_ENABLED}"
POST_SERIAL_TEST_ENABLED="${CONFIG_POST_SERIAL_TEST_ENABLED-y}"
POST_PRINTER_TEST_ENABLED="${CONFIG_POST_PRINTER_TEST_ENABLED-y}"
POST_PIC_TEST_ENABLED="${CONFIG_POST_PIC_TEST_ENABLED-y}"
POST_FLOPPY_TEST_ENABLED="${CONFIG_POST_FLOPPY_TEST_ENABLED-y}"
POST_BASE_RAM_DETECT_ENABLED="${CONFIG_POST_BASE_RAM_DETECT_ENABLED-y}"
POST_BASE_RAM_TEST_ENABLED="${CONFIG_POST_BASE_RAM_TEST_ENABLED-y}"
POST_KEYBOARD_TEST_ENABLED="${CONFIG_POST_KEYBOARD_TEST_ENABLED-y}"
POST_MOUSE_TEST_ENABLED="${CONFIG_POST_MOUSE_TEST_ENABLED-y}"

BASE_MEMORY_KB="${CONFIG_BASE_MEMORY_KB:-640}"

MACHINE_NAME="${CONFIG_MACHINE_NAME:-FreeRos PC1640 Compatible BIOS}"
BIOS_STYLE_NAME="${CONFIG_BIOS_STYLE_NAME:-PC1640-Compatible System BIOS}"

VIDEO_PEGA_STANDALONE_ROM="${CONFIG_VIDEO_PEGA_STANDALONE_ROM:-n}"
VIDEO_DIRECT_TEXT_INIT="${CONFIG_VIDEO_DIRECT_TEXT_INIT:-y}"
VIDEO_USE_PC1640_SWITCH_BLOCK="${CONFIG_VIDEO_USE_PC1640_SWITCH_BLOCK:-y}"
VIDEO_QUERY_ROM_STATE="${CONFIG_VIDEO_QUERY_ROM_STATE:-y}"
VIDEO_FIXUP_FROM_SWITCH_BLOCK="${CONFIG_VIDEO_FIXUP_FROM_SWITCH_BLOCK:-y}"
VIDEO_PEGA_INROM_DRIVER="${CONFIG_VIDEO_PEGA_INROM_DRIVER:-n}"
if [ "$VIDEO_PEGA_STANDALONE_ROM" = "y" ]; then
    VIDEO_PEGA_INROM_DRIVER="n"
fi
VIDEO_BUILTIN_TEXT=0

VIDEO_OPTION_ROM_SCAN_ENABLED="${CONFIG_VIDEO_OPTION_ROM_SCAN_ENABLED-y}"
OPTION_ROM_SCAN_ENABLED="${CONFIG_OPTION_ROM_SCAN_ENABLED-y}"
XTIDE_ENABLED="${CONFIG_XTIDE_ENABLED:-n}"
XTIDE_EMBEDDED_IN_ROS="${CONFIG_XTIDE_EMBEDDED_IN_ROS:-n}"
if [ "$XTIDE_ENABLED" != "y" ]; then
    XTIDE_EMBEDDED_IN_ROS="n"
fi
XTIDE_PROBE_MASTER="${CONFIG_XTIDE_PROBE_MASTER:-y}"
XTIDE_PROBE_SLAVE="${CONFIG_XTIDE_PROBE_SLAVE:-n}"
XTIDE_PREFER_LBA="${CONFIG_XTIDE_PREFER_LBA:-y}"
if [ "${CONFIG_XTIDE_FULL_MODE+x}" = x ]; then
    XTIDE_FULL_MODE="$CONFIG_XTIDE_FULL_MODE"
elif [ "$TARGET" = "pc1640dd" ]; then
    XTIDE_FULL_MODE="n"
else
    XTIDE_FULL_MODE="y"
fi
if [ "$XTIDE_ENABLED" != "y" ]; then
    XTIDE_EDD_ENABLED="n"
    XTIDE_COMPATIBLE_TABLES="n"
    XTIDE_BOOT_MENU_ENABLED="n"
    XTIDE_HOTKEYS_ENABLED="n"
    XTIDE_POWER_MANAGEMENT_ENABLED="n"
    XTIDE_VERY_LATE_INIT="n"
elif [ "$XTIDE_EMBEDDED_IN_ROS" = "y" ]; then
    XTIDE_EDD_ENABLED="n"
    XTIDE_COMPATIBLE_TABLES="n"
    XTIDE_BOOT_MENU_ENABLED="n"
    XTIDE_HOTKEYS_ENABLED="n"
    XTIDE_POWER_MANAGEMENT_ENABLED="n"
    XTIDE_VERY_LATE_INIT="n"
else
    if [ "$TARGET" = "pc1640dd" ]; then
        # Keep the PC1640 external XTIDE build on the small/stable XT path.
        # The motherboard BIOS publishes the legacy fixed-disk tables itself
        # after XTIDE late-init, so the option ROM does not need full mode.
        XTIDE_EDD_ENABLED="n"
        XTIDE_COMPATIBLE_TABLES="n"
        XTIDE_BOOT_MENU_ENABLED="n"
        XTIDE_HOTKEYS_ENABLED="n"
        XTIDE_POWER_MANAGEMENT_ENABLED="n"
    else
        XTIDE_EDD_ENABLED="y"
        XTIDE_COMPATIBLE_TABLES="y"
        XTIDE_BOOT_MENU_ENABLED="y"
        XTIDE_HOTKEYS_ENABLED="y"
        XTIDE_POWER_MANAGEMENT_ENABLED="y"
    fi
    XTIDE_VERY_LATE_INIT="n"
fi
XTIDE_TRANSLATION_DEFAULT=1
if [ "$XTIDE_PREFER_LBA" = "y" ]; then
    XTIDE_TRANSLATION_DEFAULT=3
fi
XTIDE_STEAL_SIZE="${CONFIG_XTIDE_STEAL_SIZE:-1}"
XTIDE_BOOT_DISPLAY_MODE="${CONFIG_XTIDE_BOOT_DISPLAY_MODE:-0004}"
XTIDE_BOOT_TIMEOUT_TICKS="${CONFIG_XTIDE_BOOT_TIMEOUT_TICKS:-546}"
XTIDE_BOOT_DRIVE="${CONFIG_XTIDE_BOOT_DRIVE:-80}"
XTIDE_MIN_FLOPPY_COUNT="${CONFIG_XTIDE_MIN_FLOPPY_COUNT:-0}"
XTIDE_CLEAR_BDA_HD_COUNT="${CONFIG_XTIDE_CLEAR_BDA_HD_COUNT:-n}"
XTIDE_SERIAL_SCAN_DETECT="${CONFIG_XTIDE_SERIAL_SCAN_DETECT:-n}"
XTIDE_IDLE_TIMEOUT="${CONFIG_XTIDE_IDLE_TIMEOUT:-0}"
XTIDE_EDD_MAX_SECTORS="${CONFIG_XTIDE_EDD_MAX_SECTORS:-127}"
XTIDE_TIMEOUT_DRQ="${CONFIG_XTIDE_TIMEOUT_DRQ:-255}"
XTIDE_TIMEOUT_BSY="${CONFIG_XTIDE_TIMEOUT_BSY:-47}"
XTIDE_TIMEOUT_DRDY="${CONFIG_XTIDE_TIMEOUT_DRDY:-47}"
XTIDE_MASTER_BLOCK_MODE="${CONFIG_XTIDE_MASTER_BLOCK_MODE:-y}"
XTIDE_MASTER_TRANSLATION_MODE="${CONFIG_XTIDE_MASTER_TRANSLATION_MODE:-$XTIDE_TRANSLATION_DEFAULT}"
XTIDE_MASTER_WRITE_CACHE="${CONFIG_XTIDE_MASTER_WRITE_CACHE:-1}"
XTIDE_MASTER_USER_CHS="${CONFIG_XTIDE_MASTER_USER_CHS:-n}"
XTIDE_MASTER_CYLINDERS="${CONFIG_XTIDE_MASTER_CYLINDERS:-1024}"
XTIDE_MASTER_HEADS="${CONFIG_XTIDE_MASTER_HEADS:-16}"
XTIDE_MASTER_SECTORS="${CONFIG_XTIDE_MASTER_SECTORS:-63}"
XTIDE_MASTER_USER_LBA="${CONFIG_XTIDE_MASTER_USER_LBA:-n}"
XTIDE_MASTER_MAX_LBA="${CONFIG_XTIDE_MASTER_MAX_LBA:-0FFFFFFF}"
XTIDE_SLAVE_BLOCK_MODE="${CONFIG_XTIDE_SLAVE_BLOCK_MODE:-y}"
XTIDE_SLAVE_TRANSLATION_MODE="${CONFIG_XTIDE_SLAVE_TRANSLATION_MODE:-$XTIDE_TRANSLATION_DEFAULT}"
XTIDE_SLAVE_WRITE_CACHE="${CONFIG_XTIDE_SLAVE_WRITE_CACHE:-1}"
XTIDE_SLAVE_USER_CHS="${CONFIG_XTIDE_SLAVE_USER_CHS:-n}"
XTIDE_SLAVE_CYLINDERS="${CONFIG_XTIDE_SLAVE_CYLINDERS:-1024}"
XTIDE_SLAVE_HEADS="${CONFIG_XTIDE_SLAVE_HEADS:-16}"
XTIDE_SLAVE_SECTORS="${CONFIG_XTIDE_SLAVE_SECTORS:-63}"
XTIDE_SLAVE_USER_LBA="${CONFIG_XTIDE_SLAVE_USER_LBA:-n}"
XTIDE_SLAVE_MAX_LBA="${CONFIG_XTIDE_SLAVE_MAX_LBA:-0FFFFFFF}"
EMS_ENABLED="${CONFIG_EMS_ENABLED:-n}"

# Determine floppy drive A type from choice variables
FLOPPY_A_TYPE="NONE"
if [ "$CONFIG_FLOPPY_A_180K" = "y" ]; then FLOPPY_A_TYPE="180K"; fi
if [ "$CONFIG_FLOPPY_A_360K" = "y" ]; then FLOPPY_A_TYPE="360K"; fi
if [ "$CONFIG_FLOPPY_A_720K" = "y" ]; then FLOPPY_A_TYPE="720K"; fi

FLOPPY_B_TYPE="NONE"
if [ "$CONFIG_FLOPPY_B_180K" = "y" ]; then FLOPPY_B_TYPE="180K"; fi
if [ "$CONFIG_FLOPPY_B_360K" = "y" ]; then FLOPPY_B_TYPE="360K"; fi
if [ "$CONFIG_FLOPPY_B_720K" = "y" ]; then FLOPPY_B_TYPE="720K"; fi

# Force floppy off if controller disabled
if [ "$CONFIG_HAS_FLOPPY_CONTROLLER" != "y" ]; then
    FLOPPY_A_TYPE="NONE"
    FLOPPY_B_TYPE="NONE"
fi

FLOPPY_DRIVES=0
if [ "$FLOPPY_A_TYPE" != "NONE" ]; then FLOPPY_DRIVES=$((FLOPPY_DRIVES + 1)); fi
if [ "$FLOPPY_B_TYPE" != "NONE" ]; then FLOPPY_DRIVES=$((FLOPPY_DRIVES + 1)); fi

# INT 19h fixed disk (80h): always on for embedded XTIDE, when the user enables
# it in menuconfig, or when there is no floppy boot path (no FDC or zero drives).
if [ "$XTIDE_ENABLED" = "y" ] || [ "${CONFIG_HD_BOOT_ENABLED:-n}" = "y" ]; then
    HD_BOOT_ENABLED="y"
elif [ "$CONFIG_HAS_FLOPPY_CONTROLLER" != "y" ] || [ "$FLOPPY_DRIVES" = "0" ]; then
    HD_BOOT_ENABLED="y"
else
    HD_BOOT_ENABLED="n"
fi

# Determine video equipment
VIDEO_EQUIPMENT="BIOS_CFG_VIDEO_EQUIPMENT_80X25_COLOR"
if [ "$CONFIG_VIDEO_EGA_ADAPTER" = "y" ]; then VIDEO_EQUIPMENT="BIOS_CFG_VIDEO_EQUIPMENT_EGA_ADAPTER"; fi
if [ "$CONFIG_VIDEO_40X25_COLOR" = "y" ]; then VIDEO_EQUIPMENT="BIOS_CFG_VIDEO_EQUIPMENT_40X25_COLOR"; fi
if [ "$CONFIG_VIDEO_80X25_COLOR" = "y" ]; then VIDEO_EQUIPMENT="BIOS_CFG_VIDEO_EQUIPMENT_80X25_COLOR"; fi
if [ "$CONFIG_VIDEO_MONO" = "y" ]; then VIDEO_EQUIPMENT="BIOS_CFG_VIDEO_EQUIPMENT_MONO"; fi

# --- Generate header ---
{
    echo "#ifndef FREEROS_CONFIG_AUTOGEN_H"
    echo "#define FREEROS_CONFIG_AUTOGEN_H"
    echo ""
    echo "/* Autogenerated by scripts/mkconfig.sh from .config */"
    echo ""

    # Identity
    emit_str "BIOS_CFG_MACHINE_NAME" "${MACHINE_NAME}"
    emit_str "BIOS_CFG_BIOS_BRAND" "${CONFIG_BIOS_BRAND}"
    emit_str "BIOS_CFG_BIOS_STYLE_NAME" "${BIOS_STYLE_NAME}"
    emit_str "BIOS_CFG_WEBSITE" "${CONFIG_WEBSITE}"
    emit "BIOS_CFG_TARGET_PC1640DD" "1"

    # Hardware
    emit "BIOS_CFG_BASE_MEMORY_KB" "${BASE_MEMORY_KB}"
    emit "BIOS_CFG_HAS_PARADISE_PEGA1A" "$(bool_val "$HAS_PARADISE_PEGA1A")"
    emit "BIOS_CFG_HAS_AMSTRAD_MOUSE" "$(bool_val "$HAS_AMSTRAD_MOUSE")"
    emit "BIOS_CFG_HAS_BATTERY_BACKED_RTC" "$(bool_val "$HAS_BATTERY_BACKED_RTC")"
    emit "BIOS_CFG_HAS_MATH_COPROCESSOR" "$(bool_val "$CONFIG_HAS_MATH_COPROCESSOR")"
    emit "BIOS_CFG_HAS_DMA_CONTROLLER" "$(bool_val "$HAS_DMA_CONTROLLER")"
    emit "BIOS_CFG_POST_ROS_CHECKSUM_TEST_ENABLED" "$(bool_val "$POST_ROS_CHECKSUM_TEST_ENABLED")"
    emit "BIOS_CFG_POST_VIDEO_MEMORY_TEST_ENABLED" "$(bool_val "$POST_VIDEO_MEMORY_TEST_ENABLED")"
    emit "BIOS_CFG_POST_DMA_TEST_ENABLED" "$(bool_val "$POST_DMA_TEST_ENABLED")"
    emit "BIOS_CFG_POST_TIMER_TEST_ENABLED" "$(bool_val "$POST_TIMER_TEST_ENABLED")"
    emit "BIOS_CFG_POST_SYSTEM_STATUS_TEST_ENABLED" "$(bool_val "$POST_SYSTEM_STATUS_TEST_ENABLED")"
    emit "BIOS_CFG_POST_RTC_TEST_ENABLED" "$(bool_val "$POST_RTC_TEST_ENABLED")"
    emit "BIOS_CFG_POST_SERIAL_TEST_ENABLED" "$(bool_val "$POST_SERIAL_TEST_ENABLED")"
    emit "BIOS_CFG_POST_PRINTER_TEST_ENABLED" "$(bool_val "$POST_PRINTER_TEST_ENABLED")"
    emit "BIOS_CFG_POST_PIC_TEST_ENABLED" "$(bool_val "$POST_PIC_TEST_ENABLED")"
    emit "BIOS_CFG_POST_FLOPPY_TEST_ENABLED" "$(bool_val "$POST_FLOPPY_TEST_ENABLED")"
    emit "BIOS_CFG_POST_BASE_RAM_DETECT_ENABLED" "$(bool_val "$POST_BASE_RAM_DETECT_ENABLED")"
    emit "BIOS_CFG_POST_BASE_RAM_TEST_ENABLED" "$(bool_val "$POST_BASE_RAM_TEST_ENABLED")"
    emit "BIOS_CFG_POST_KEYBOARD_TEST_ENABLED" "$(bool_val "$POST_KEYBOARD_TEST_ENABLED")"
    emit "BIOS_CFG_POST_MOUSE_TEST_ENABLED" "$(bool_val "$POST_MOUSE_TEST_ENABLED")"

    # Ports
    emit "BIOS_CFG_COM1_BASE" "0x$(strip_0x "${CONFIG_COM1_BASE:-03F8}")"
    emit "BIOS_CFG_COM2_BASE" "0x$(strip_0x "${CONFIG_COM2_BASE:-02F8}")"
    emit "BIOS_CFG_LPT1_BASE" "0x$(strip_0x "${CONFIG_LPT1_BASE:-0378}")"
    emit "BIOS_CFG_LPT2_BASE" "0x$(strip_0x "${CONFIG_LPT2_BASE:-03BC}")"

    # Video
    emit "BIOS_CFG_VIDEO_EQUIPMENT" "$VIDEO_EQUIPMENT"
    emit "BIOS_CFG_VIDEO_ATTRIBUTE" "0x$(strip_0x "${CONFIG_VIDEO_ATTRIBUTE:-07}")"
    emit "BIOS_CFG_VIDEO_OPTION_ROM_SCAN_ENABLED" "$(bool_val "$VIDEO_OPTION_ROM_SCAN_ENABLED")"
    emit "BIOS_CFG_OPTION_ROM_SCAN_ENABLED" "$(bool_val "$OPTION_ROM_SCAN_ENABLED")"
    emit "BIOS_CFG_VIDEO_OPTION_ROM_SCAN_START" "$VIDEO_OPTION_ROM_SCAN_START"
    emit "BIOS_CFG_VIDEO_OPTION_ROM_SCAN_END" "$VIDEO_OPTION_ROM_SCAN_END"
    emit "BIOS_CFG_VIDEO_OPTION_ROM_SCAN_STEP" "0x0080"
    emit "BIOS_CFG_OPTION_ROM_SCAN_START" "$OPTION_ROM_SCAN_START"
    emit "BIOS_CFG_OPTION_ROM_SCAN_END" "$OPTION_ROM_SCAN_END"
    emit "BIOS_CFG_OPTION_ROM_SCAN_STEP" "0x0080"
    emit "BIOS_CFG_VIDEO_DIRECT_TEXT_INIT" "$(bool_val "$VIDEO_DIRECT_TEXT_INIT")"
    emit "BIOS_CFG_VIDEO_USE_PC1640_SWITCH_BLOCK" "$(bool_val "$VIDEO_USE_PC1640_SWITCH_BLOCK")"
    emit "BIOS_CFG_VIDEO_QUERY_ROM_STATE" "$(bool_val "$VIDEO_QUERY_ROM_STATE")"
    emit "BIOS_CFG_VIDEO_FIXUP_FROM_SWITCH_BLOCK" "$(bool_val "$VIDEO_FIXUP_FROM_SWITCH_BLOCK")"
    emit "BIOS_CFG_VIDEO_PEGA_INROM_DRIVER" "$(bool_val "$VIDEO_PEGA_INROM_DRIVER")"
    emit "BIOS_CFG_VIDEO_PEGA_STANDALONE_ROM_BUILD" "$(bool_val "$VIDEO_PEGA_STANDALONE_ROM")"
    emit "BIOS_CFG_VIDEO_BUILTIN_TEXT" "$VIDEO_BUILTIN_TEXT"
    emit "BIOS_CFG_ROM_ENTRY_SEGMENT" "$ROM_ENTRY_SEGMENT"
    emit "BIOS_CFG_ROM_IMAGE_SIZE" "$ROM_IMAGE_SIZE"
    emit "BIOS_CFG_EXECUTE_IN_PLACE" "$(bool_val "$EXECUTE_IN_PLACE")"
    emit "BIOS_CFG_RUNTIME_SEGMENT" "$RUNTIME_SEGMENT"
    emit "BIOS_CFG_STACK_SEGMENT" "$STACK_SEGMENT"
    emit "BIOS_CFG_STACK_OFFSET" "$STACK_OFFSET"

    # Floppy
    emit "BIOS_CFG_HAS_FLOPPY_CONTROLLER" "$(bool_val "$CONFIG_HAS_FLOPPY_CONTROLLER")"
    emit "BIOS_CFG_FLOPPY_SUPPORT_35_DD" "$(bool_val "$CONFIG_FLOPPY_SUPPORT_35DD")"
    emit "BIOS_CFG_FLOPPY_PROFILE" "BIOS_FLOPPY_PROFILE_CUSTOM"
    emit "BIOS_CFG_FLOPPY_TYPE_A" "$(floppy_type_macro "$FLOPPY_A_TYPE")"
    emit "BIOS_CFG_FLOPPY_TYPE_B" "$(floppy_type_macro "$FLOPPY_B_TYPE")"
    emit "BIOS_CFG_FLOPPY_DRIVES" "$FLOPPY_DRIVES"
    emit "BIOS_CFG_FLOPPY_ENABLE_AH08_COMPAT" "$(bool_val "$CONFIG_FLOPPY_ENABLE_AH08_COMPAT")"

    # Interrupt services
    emit "BIOS_CFG_SERIAL_INT14_ENABLED" "$(bool_val "$CONFIG_SERIAL_INT14_ENABLED")"
    emit "BIOS_CFG_PRINTER_ENABLED" "$(bool_val "$CONFIG_PRINTER_ENABLED")"

    # EMS
    emit "BIOS_CFG_EMS_ENABLED" "$(bool_val "$EMS_ENABLED")"
    emit "BIOS_CFG_EMS_IO_BASE" "0x$(strip_0x "${CONFIG_EMS_IO_BASE:-0260}")"
    emit "BIOS_CFG_EMS_FRAME_SEGMENT" "0x$(strip_0x "${CONFIG_EMS_FRAME_SEGMENT:-D000}")"

    # IDE
    emit "BIOS_CFG_XTIDE_ENABLED" "$(bool_val "$XTIDE_ENABLED")"
    emit "BIOS_CFG_XTIDE_EMBEDDED_IN_ROS" "$(bool_val "$XTIDE_EMBEDDED_IN_ROS")"
    emit "BIOS_CFG_XTIDE_BASE" "0x$(strip_0x "${CONFIG_XTIDE_BASE:-0300}")"
    emit "BIOS_CFG_XTIDE_PROBE_MASTER" "$(bool_val "$XTIDE_PROBE_MASTER")"
    emit "BIOS_CFG_XTIDE_PROBE_SLAVE" "$(bool_val "$XTIDE_PROBE_SLAVE")"
    emit "BIOS_CFG_XTIDE_PREFER_LBA" "$(bool_val "$XTIDE_PREFER_LBA")"
    emit "BIOS_CFG_XTIDE_FULL_MODE" "$(bool_val "$XTIDE_FULL_MODE")"
    emit "BIOS_CFG_XTIDE_STEAL_SIZE" "${XTIDE_STEAL_SIZE}"
    emit "BIOS_CFG_XTIDE_EDD_ENABLED" "$(bool_val "$XTIDE_EDD_ENABLED")"
    emit "BIOS_CFG_XTIDE_COMPATIBLE_TABLES" "$(bool_val "$XTIDE_COMPATIBLE_TABLES")"
    emit "BIOS_CFG_XTIDE_BOOT_MENU_ENABLED" "$(bool_val "$XTIDE_BOOT_MENU_ENABLED")"
    emit "BIOS_CFG_XTIDE_HOTKEYS_ENABLED" "$(bool_val "$XTIDE_HOTKEYS_ENABLED")"
    emit "BIOS_CFG_XTIDE_POWER_MANAGEMENT_ENABLED" "$(bool_val "$XTIDE_POWER_MANAGEMENT_ENABLED")"
    emit "BIOS_CFG_XTIDE_VERY_LATE_INIT" "$(bool_val "$XTIDE_VERY_LATE_INIT")"
    emit "BIOS_CFG_XTIDE_BOOT_DISPLAY_MODE" "0x$(strip_0x "${XTIDE_BOOT_DISPLAY_MODE}")"
    emit "BIOS_CFG_XTIDE_BOOT_TIMEOUT_TICKS" "${XTIDE_BOOT_TIMEOUT_TICKS}"
    emit "BIOS_CFG_XTIDE_BOOT_DRIVE" "0x$(strip_0x "${XTIDE_BOOT_DRIVE}")"
    emit "BIOS_CFG_XTIDE_MIN_FLOPPY_COUNT" "${XTIDE_MIN_FLOPPY_COUNT}"
    emit "BIOS_CFG_XTIDE_CLEAR_BDA_HD_COUNT" "$(bool_val "$XTIDE_CLEAR_BDA_HD_COUNT")"
    emit "BIOS_CFG_XTIDE_SERIAL_SCAN_DETECT" "$(bool_val "$XTIDE_SERIAL_SCAN_DETECT")"
    emit "BIOS_CFG_XTIDE_IDLE_TIMEOUT" "${XTIDE_IDLE_TIMEOUT}"
    emit "BIOS_CFG_XTIDE_EDD_MAX_SECTORS" "${XTIDE_EDD_MAX_SECTORS}"
    emit "BIOS_CFG_XTIDE_TIMEOUT_DRQ" "${XTIDE_TIMEOUT_DRQ}"
    emit "BIOS_CFG_XTIDE_TIMEOUT_BSY" "${XTIDE_TIMEOUT_BSY}"
    emit "BIOS_CFG_XTIDE_TIMEOUT_DRDY" "${XTIDE_TIMEOUT_DRDY}"
    emit "BIOS_CFG_XTIDE_MASTER_BLOCK_MODE" "$(bool_val "$XTIDE_MASTER_BLOCK_MODE")"
    emit "BIOS_CFG_XTIDE_MASTER_TRANSLATION_MODE" "${XTIDE_MASTER_TRANSLATION_MODE}"
    emit "BIOS_CFG_XTIDE_MASTER_WRITE_CACHE" "${XTIDE_MASTER_WRITE_CACHE}"
    emit "BIOS_CFG_XTIDE_MASTER_USER_CHS" "$(bool_val "$XTIDE_MASTER_USER_CHS")"
    emit "BIOS_CFG_XTIDE_MASTER_CYLINDERS" "${XTIDE_MASTER_CYLINDERS}"
    emit "BIOS_CFG_XTIDE_MASTER_HEADS" "${XTIDE_MASTER_HEADS}"
    emit "BIOS_CFG_XTIDE_MASTER_SECTORS" "${XTIDE_MASTER_SECTORS}"
    emit "BIOS_CFG_XTIDE_MASTER_USER_LBA" "$(bool_val "$XTIDE_MASTER_USER_LBA")"
    emit "BIOS_CFG_XTIDE_MASTER_MAX_LBA" "0x$(strip_0x "${XTIDE_MASTER_MAX_LBA}")"
    emit "BIOS_CFG_XTIDE_SLAVE_BLOCK_MODE" "$(bool_val "$XTIDE_SLAVE_BLOCK_MODE")"
    emit "BIOS_CFG_XTIDE_SLAVE_TRANSLATION_MODE" "${XTIDE_SLAVE_TRANSLATION_MODE}"
    emit "BIOS_CFG_XTIDE_SLAVE_WRITE_CACHE" "${XTIDE_SLAVE_WRITE_CACHE}"
    emit "BIOS_CFG_XTIDE_SLAVE_USER_CHS" "$(bool_val "$XTIDE_SLAVE_USER_CHS")"
    emit "BIOS_CFG_XTIDE_SLAVE_CYLINDERS" "${XTIDE_SLAVE_CYLINDERS}"
    emit "BIOS_CFG_XTIDE_SLAVE_HEADS" "${XTIDE_SLAVE_HEADS}"
    emit "BIOS_CFG_XTIDE_SLAVE_SECTORS" "${XTIDE_SLAVE_SECTORS}"
    emit "BIOS_CFG_XTIDE_SLAVE_USER_LBA" "$(bool_val "$XTIDE_SLAVE_USER_LBA")"
    emit "BIOS_CFG_XTIDE_SLAVE_MAX_LBA" "0x$(strip_0x "${XTIDE_SLAVE_MAX_LBA}")"

    emit "BIOS_CFG_HD_BOOT_ENABLED" "$(bool_val "$HD_BOOT_ENABLED")"

    # RTC
    emit "BIOS_CFG_ROS_RELEASE" "${CONFIG_ROS_RELEASE:-0}"
    emit "BIOS_CFG_ROS_ISSUE" "${CONFIG_ROS_ISSUE:-2}"
    emit "BIOS_CFG_UART_INIT" "0x$(strip_0x "${CONFIG_UART_INIT:-E3}")"
    emit "BIOS_CFG_RTC_DEFAULT_SECONDS" "${CONFIG_RTC_DEFAULT_SECONDS:-0}"
    emit "BIOS_CFG_RTC_DEFAULT_MINUTES" "${CONFIG_RTC_DEFAULT_MINUTES:-0}"
    emit "BIOS_CFG_RTC_DEFAULT_HOURS" "${CONFIG_RTC_DEFAULT_HOURS:-0}"
    emit "BIOS_CFG_RTC_DEFAULT_DAY_OF_MONTH" "${CONFIG_RTC_DEFAULT_DAY_OF_MONTH:-1}"
    emit "BIOS_CFG_RTC_DEFAULT_MONTH" "${CONFIG_RTC_DEFAULT_MONTH:-1}"
    emit "BIOS_CFG_RTC_DEFAULT_YEAR" "${CONFIG_RTC_DEFAULT_YEAR:-88}"
    emit "BIOS_CFG_RTC_DEFAULT_CENTURY" "${CONFIG_RTC_DEFAULT_CENTURY:-19}"
    emit "BIOS_CFG_PC1640_NVR_ENTER_TOKEN" "0x$(strip_0x "${CONFIG_PC1640_NVR_ENTER_TOKEN:-1C0D}")"
    emit "BIOS_CFG_PC1640_NVR_DELETE_TOKEN" "0x$(strip_0x "${CONFIG_PC1640_NVR_DELETE_TOKEN:-2207}")"
    emit "BIOS_CFG_PC1640_NVR_JOYSTICK1_TOKEN" "0x$(strip_0x "${CONFIG_PC1640_NVR_JOYSTICK1_TOKEN:-FFFF}")"
    emit "BIOS_CFG_PC1640_NVR_JOYSTICK2_TOKEN" "0x$(strip_0x "${CONFIG_PC1640_NVR_JOYSTICK2_TOKEN:-FFFF}")"
    emit "BIOS_CFG_PC1640_NVR_MOUSE1_TOKEN" "0x$(strip_0x "${CONFIG_PC1640_NVR_MOUSE1_TOKEN:-FFFF}")"
    emit "BIOS_CFG_PC1640_NVR_MOUSE2_TOKEN" "0x$(strip_0x "${CONFIG_PC1640_NVR_MOUSE2_TOKEN:-FFFF}")"
    emit "BIOS_CFG_PC1640_NVR_MOUSE_X_SCALE" "${CONFIG_PC1640_NVR_MOUSE_X_SCALE:-10}"
    emit "BIOS_CFG_PC1640_NVR_MOUSE_Y_SCALE" "${CONFIG_PC1640_NVR_MOUSE_Y_SCALE:-10}"
    emit "BIOS_CFG_PC1640_NVR_RAMDISK_SIZE" "0x$(strip_0x "${CONFIG_PC1640_NVR_RAMDISK_SIZE:-00}")"

    # BIOS mode
    if [ "$CONFIG_MODE_ELKS" = "y" ]; then
        emit "BIOS_CFG_MODE_ELKS" "1"
    else
        emit "BIOS_CFG_MODE_ELKS" "0"
    fi

    # Initial banner (stock PC1640 path)
    emit "BIOS_CFG_INITIAL_BANNER_ENABLED" "0"
    BANNER_STYLE=1
    if [ "$CONFIG_BANNER_STYLE_AMSTRAD_PLAIN" = "y" ]; then BANNER_STYLE=2; fi
    if [ "$CONFIG_BANNER_STYLE_AMSTRAD_BACKSLASH" = "y" ]; then BANNER_STYLE=3; fi
    if [ "$CONFIG_BANNER_STYLE_AMSTRAD_BUBBLE" = "y" ]; then BANNER_STYLE=4; fi
    emit "BIOS_CFG_INITIAL_BANNER_STYLE" "$BANNER_STYLE"
    emit "BIOS_CFG_INITIAL_BANNER_TIMEOUT" "${CONFIG_INITIAL_BANNER_TIMEOUT:-2}"

    # POST (Amstrad plain text path)
    emit "BIOS_CFG_POST_PRETTY_WAIT_PANEL" "0"
    emit "BIOS_CFG_POST_SPACE_INVADERS_SOUND" "$(bool_val "$CONFIG_POST_SPACE_INVADERS_SOUND")"

    # Debug routing and overlays
    emit "BIOS_CFG_DEBUG_PORT_E9" "$(bool_val "$CONFIG_DEBUG_PORT_E9")"
    emit "BIOS_CFG_DEBUG_COM1" "$(bool_val "$CONFIG_DEBUG_COM1")"
    emit "BIOS_CFG_DEBUG_VIDEO_STATE" "$(bool_val "$CONFIG_DEBUG_VIDEO_STATE")"
    emit "BIOS_CFG_DEBUG_VIDEO_OVERLAY" "$(bool_val "$CONFIG_DEBUG_VIDEO_OVERLAY")"
    emit "BIOS_CFG_TRACE_VIDEO_COM1" "$(bool_val "$CONFIG_TRACE_VIDEO_COM1")"

    echo ""
    echo "#endif"
} > "$HEADER"

# --- Generate config.mk ---
{
    echo "# Autogenerated by scripts/mkconfig.sh from .config"

    # Boot floppy image
    BOOT_IMG=""
    if [ "$CONFIG_HAS_FLOPPY_CONTROLLER" = "y" ]; then
        if [ "$FLOPPY_A_TYPE" = "720K" ]; then
            BOOT_IMG="test_media/svdos-720K-disk-1.img"
        elif [ "$FLOPPY_A_TYPE" = "360K" ]; then
            BOOT_IMG="test_media/ibm_dos_330_disk1_360k.img"
        fi
    fi
    echo "CONFIG_BOOT_FLOPPY_IMAGE := $BOOT_IMG"
    echo "CONFIG_FLOPPY_DRIVES := $FLOPPY_DRIVES"
    echo "CONFIG_MACHINE_TARGET := $TARGET"
    echo "CONFIG_MACHINE_SRC := $MACHINE_SRC"
    if [ "$VIDEO_PEGA_INROM_DRIVER" = "y" ]; then
        echo "CONFIG_VIDEO_PEGA_INROM_DRIVER := y"
    else
        echo "CONFIG_VIDEO_PEGA_INROM_DRIVER :="
    fi
    if [ "$VIDEO_PEGA_STANDALONE_ROM" = "y" ]; then
        echo "CONFIG_VIDEO_PEGA_STANDALONE_ROM := y"
    else
        echo "CONFIG_VIDEO_PEGA_STANDALONE_ROM :="
    fi
    echo "CONFIG_ROM_LAYOUT := $ROM_LAYOUT"
    echo "CONFIG_ROM_ENTRY_SEGMENT := $ROM_ENTRY_SEGMENT"
    echo "CONFIG_ROM_IMAGE_SIZE := $ROM_IMAGE_SIZE"
    echo "CONFIG_ROM_MACHINE_ID_BYTE := $ROM_MACHINE_ID_BYTE"
    if [ -n "$EXECUTE_IN_PLACE" ]; then
        echo "CONFIG_EXECUTE_IN_PLACE := y"
    else
        echo "CONFIG_EXECUTE_IN_PLACE :="
    fi
    echo "CONFIG_RUNTIME_SEGMENT := $RUNTIME_SEGMENT"
    echo "CONFIG_STACK_SEGMENT := $STACK_SEGMENT"
    echo "CONFIG_STACK_OFFSET := $STACK_OFFSET"
    echo "CONFIG_ROM_COMPAT_HOLE_OFFSET := $ROM_COMPAT_HOLE_OFFSET"
    echo "CONFIG_ROM_COMPAT_HOLE_SIZE := $ROM_COMPAT_HOLE_SIZE"
    if [ -n "$ROM_COMPAT_PATCH_ENABLED" ]; then
        echo "CONFIG_ROM_COMPAT_PATCH_ENABLED := y"
    else
        echo "CONFIG_ROM_COMPAT_PATCH_ENABLED :="
    fi
    if [ -n "$ROM_ROS_CHECKSUM_ENABLED" ]; then
        echo "CONFIG_ROM_ROS_CHECKSUM_ENABLED := y"
    else
        echo "CONFIG_ROM_ROS_CHECKSUM_ENABLED :="
    fi

    if [ "$CONFIG_SERIAL_INT14_ENABLED" = "y" ]; then
        echo "CONFIG_SERIAL_INT14_ENABLED := y"
    else
        echo "CONFIG_SERIAL_INT14_ENABLED :="
    fi
    if [ "$CONFIG_PRINTER_ENABLED" = "y" ]; then
        echo "CONFIG_PRINTER_ENABLED := y"
    else
        echo "CONFIG_PRINTER_ENABLED :="
    fi
    if [ "$EMS_ENABLED" = "y" ]; then
        echo "CONFIG_EMS_ENABLED := y"
    else
        echo "CONFIG_EMS_ENABLED :="
    fi

    # BIOS mode
    if [ "$CONFIG_MODE_ELKS" = "y" ]; then
        echo "CONFIG_MODE_ELKS := y"
    else
        echo "CONFIG_MODE_ELKS :="
    fi

    # XTIDE
    if [ "$XTIDE_ENABLED" = "y" ]; then
        echo "CONFIG_XTIDE_ENABLED := y"
        if [ "$XTIDE_EMBEDDED_IN_ROS" = "y" ]; then
            echo "CONFIG_XTIDE_EMBEDDED_IN_ROS := y"
        else
            echo "CONFIG_XTIDE_EMBEDDED_IN_ROS :="
        fi
        echo "CONFIG_XTIDE_BASE := $(strip_0x "${CONFIG_XTIDE_BASE:-0300}")"
        echo "CONFIG_XTIDE_PROBE_MASTER := $(if [ "$XTIDE_PROBE_MASTER" = "y" ]; then echo y; fi)"
        echo "CONFIG_XTIDE_PROBE_SLAVE := $(if [ "$XTIDE_PROBE_SLAVE" = "y" ]; then echo y; fi)"
        echo "CONFIG_XTIDE_PREFER_LBA := $(if [ "$XTIDE_PREFER_LBA" = "y" ]; then echo y; fi)"
        echo "CONFIG_XTIDE_FULL_MODE := $(if [ "$XTIDE_FULL_MODE" = "y" ]; then echo y; fi)"
        echo "CONFIG_XTIDE_STEAL_SIZE := ${XTIDE_STEAL_SIZE}"
        echo "CONFIG_XTIDE_EDD_ENABLED := $(if [ "$XTIDE_EDD_ENABLED" = "y" ]; then echo y; fi)"
        echo "CONFIG_XTIDE_COMPATIBLE_TABLES := $(if [ "$XTIDE_COMPATIBLE_TABLES" = "y" ]; then echo y; fi)"
        echo "CONFIG_XTIDE_BOOT_MENU_ENABLED := $(if [ "$XTIDE_BOOT_MENU_ENABLED" = "y" ]; then echo y; fi)"
        echo "CONFIG_XTIDE_HOTKEYS_ENABLED := $(if [ "$XTIDE_HOTKEYS_ENABLED" = "y" ]; then echo y; fi)"
        echo "CONFIG_XTIDE_POWER_MANAGEMENT_ENABLED := $(if [ "$XTIDE_POWER_MANAGEMENT_ENABLED" = "y" ]; then echo y; fi)"
        echo "CONFIG_XTIDE_VERY_LATE_INIT := $(if [ "$XTIDE_VERY_LATE_INIT" = "y" ]; then echo y; fi)"
        echo "CONFIG_XTIDE_BOOT_DISPLAY_MODE := $(strip_0x "${XTIDE_BOOT_DISPLAY_MODE}")"
        echo "CONFIG_XTIDE_BOOT_TIMEOUT_TICKS := ${XTIDE_BOOT_TIMEOUT_TICKS}"
        echo "CONFIG_XTIDE_BOOT_DRIVE := $(strip_0x "${XTIDE_BOOT_DRIVE}")"
        echo "CONFIG_XTIDE_MIN_FLOPPY_COUNT := ${XTIDE_MIN_FLOPPY_COUNT}"
        echo "CONFIG_XTIDE_CLEAR_BDA_HD_COUNT := $(if [ "$XTIDE_CLEAR_BDA_HD_COUNT" = "y" ]; then echo y; fi)"
        echo "CONFIG_XTIDE_SERIAL_SCAN_DETECT := $(if [ "$XTIDE_SERIAL_SCAN_DETECT" = "y" ]; then echo y; fi)"
        echo "CONFIG_XTIDE_IDLE_TIMEOUT := ${XTIDE_IDLE_TIMEOUT}"
        echo "CONFIG_XTIDE_EDD_MAX_SECTORS := ${XTIDE_EDD_MAX_SECTORS}"
        echo "CONFIG_XTIDE_TIMEOUT_DRQ := ${XTIDE_TIMEOUT_DRQ}"
        echo "CONFIG_XTIDE_TIMEOUT_BSY := ${XTIDE_TIMEOUT_BSY}"
        echo "CONFIG_XTIDE_TIMEOUT_DRDY := ${XTIDE_TIMEOUT_DRDY}"
        echo "CONFIG_XTIDE_MASTER_BLOCK_MODE := $(if [ "$XTIDE_MASTER_BLOCK_MODE" = "y" ]; then echo y; fi)"
        echo "CONFIG_XTIDE_MASTER_TRANSLATION_MODE := ${XTIDE_MASTER_TRANSLATION_MODE}"
        echo "CONFIG_XTIDE_MASTER_WRITE_CACHE := ${XTIDE_MASTER_WRITE_CACHE}"
        echo "CONFIG_XTIDE_MASTER_USER_CHS := $(if [ "$XTIDE_MASTER_USER_CHS" = "y" ]; then echo y; fi)"
        echo "CONFIG_XTIDE_MASTER_CYLINDERS := ${XTIDE_MASTER_CYLINDERS}"
        echo "CONFIG_XTIDE_MASTER_HEADS := ${XTIDE_MASTER_HEADS}"
        echo "CONFIG_XTIDE_MASTER_SECTORS := ${XTIDE_MASTER_SECTORS}"
        echo "CONFIG_XTIDE_MASTER_USER_LBA := $(if [ "$XTIDE_MASTER_USER_LBA" = "y" ]; then echo y; fi)"
        echo "CONFIG_XTIDE_MASTER_MAX_LBA := $(strip_0x "${XTIDE_MASTER_MAX_LBA}")"
        echo "CONFIG_XTIDE_SLAVE_BLOCK_MODE := $(if [ "$XTIDE_SLAVE_BLOCK_MODE" = "y" ]; then echo y; fi)"
        echo "CONFIG_XTIDE_SLAVE_TRANSLATION_MODE := ${XTIDE_SLAVE_TRANSLATION_MODE}"
        echo "CONFIG_XTIDE_SLAVE_WRITE_CACHE := ${XTIDE_SLAVE_WRITE_CACHE}"
        echo "CONFIG_XTIDE_SLAVE_USER_CHS := $(if [ "$XTIDE_SLAVE_USER_CHS" = "y" ]; then echo y; fi)"
        echo "CONFIG_XTIDE_SLAVE_CYLINDERS := ${XTIDE_SLAVE_CYLINDERS}"
        echo "CONFIG_XTIDE_SLAVE_HEADS := ${XTIDE_SLAVE_HEADS}"
        echo "CONFIG_XTIDE_SLAVE_SECTORS := ${XTIDE_SLAVE_SECTORS}"
        echo "CONFIG_XTIDE_SLAVE_USER_LBA := $(if [ "$XTIDE_SLAVE_USER_LBA" = "y" ]; then echo y; fi)"
        echo "CONFIG_XTIDE_SLAVE_MAX_LBA := $(strip_0x "${XTIDE_SLAVE_MAX_LBA}")"
    else
        echo "CONFIG_XTIDE_ENABLED :="
        echo "CONFIG_XTIDE_EMBEDDED_IN_ROS :="
    fi

    # Debug defines
    echo "CONFIG_BIOS_DEBUG_DEFS :="
    if [ "$CONFIG_DEBUG_PORT_E9" = "y" ]; then
        echo "CONFIG_BIOS_DEBUG_DEFS += -DBIOS_CFG_DEBUG_PORT_E9=1"
    fi
    if [ "$CONFIG_DEBUG_COM1" = "y" ]; then
        echo "CONFIG_BIOS_DEBUG_DEFS += -DBIOS_CFG_DEBUG_COM1=1"
    fi
    if [ "$CONFIG_DEBUG_VIDEO_STATE" = "y" ]; then
        echo "CONFIG_BIOS_DEBUG_DEFS += -DBIOS_CFG_DEBUG_VIDEO_STATE=1"
    fi
    if [ "$CONFIG_DEBUG_VIDEO_OVERLAY" = "y" ]; then
        echo "CONFIG_BIOS_DEBUG_DEFS += -DBIOS_CFG_DEBUG_VIDEO_OVERLAY=1"
    fi
    if [ "$CONFIG_TRACE_VIDEO_COM1" = "y" ]; then
        echo "CONFIG_BIOS_DEBUG_DEFS += -DBIOS_CFG_TRACE_VIDEO_COM1=1"
    fi
} > "$MAKEFILE"
