#!/bin/bash
#
# Generate build/config_autogen.h and build/config.mk from .config
#
# This translates Kconfig-style CONFIG_* names into the BIOS_CFG_*
# names expected by the BIOS source code.
#

set -e

CONFIG="${1:-.config}"
HEADER="${2:-build/config_autogen.h}"
MAKEFILE="${3:-build/config.mk}"

if [ ! -f "$CONFIG" ]; then
    echo "mkconfig.sh: $CONFIG not found" >&2
    exit 1
fi

mkdir -p "$(dirname "$HEADER")" "$(dirname "$MAKEFILE")"

. "$CONFIG"

# --- Helper: emit a #define ---
emit() {
    echo "#undef  $1"
    echo "#define $1 $2"
}

emit_str() {
    echo "#undef  $1"
    echo "#define $1 \"$2\""
}

bool_val() {
    if [ "$1" = "y" ]; then echo 1; else echo 0; fi
}

# Strip 0x prefix if present (Kconfig hex values include it)
strip_0x() {
    echo "${1#0x}"
}

# --- Floppy drive type mapping ---
floppy_type_macro() {
    case "$1" in
        360K) echo "BIOS_FLOPPY_TYPE_360K_525DD" ;;
        720K) echo "BIOS_FLOPPY_TYPE_720K_35DD" ;;
        *)    echo "BIOS_FLOPPY_TYPE_NONE" ;;
    esac
}

# Determine floppy drive A type from choice variables
FLOPPY_A_TYPE="NONE"
if [ "$CONFIG_FLOPPY_A_360K" = "y" ]; then FLOPPY_A_TYPE="360K"; fi
if [ "$CONFIG_FLOPPY_A_720K" = "y" ]; then FLOPPY_A_TYPE="720K"; fi

FLOPPY_B_TYPE="NONE"
if [ "$CONFIG_FLOPPY_B_360K" = "y" ]; then FLOPPY_B_TYPE="360K"; fi
if [ "$CONFIG_FLOPPY_B_720K" = "y" ]; then FLOPPY_B_TYPE="720K"; fi

# Force floppy off if controller disabled
if [ "$CONFIG_HAS_FLOPPY_CONTROLLER" != "y" ]; then
    FLOPPY_A_TYPE="NONE"
    FLOPPY_B_TYPE="NONE"
fi

FLOPPY_DRIVES=0
if [ "$FLOPPY_A_TYPE" != "NONE" ]; then FLOPPY_DRIVES=$((FLOPPY_DRIVES + 1)); fi
if [ "$FLOPPY_B_TYPE" != "NONE" ]; then FLOPPY_DRIVES=$((FLOPPY_DRIVES + 1)); fi

# Determine video equipment
VIDEO_EQUIPMENT="BIOS_CFG_VIDEO_EQUIPMENT_80X25_COLOR"
if [ "$CONFIG_VIDEO_EGA_ADAPTER" = "y" ]; then VIDEO_EQUIPMENT="BIOS_CFG_VIDEO_EQUIPMENT_EGA_ADAPTER"; fi
if [ "$CONFIG_VIDEO_40X25_COLOR" = "y" ]; then VIDEO_EQUIPMENT="BIOS_CFG_VIDEO_EQUIPMENT_40X25_COLOR"; fi
if [ "$CONFIG_VIDEO_80X25_COLOR" = "y" ]; then VIDEO_EQUIPMENT="BIOS_CFG_VIDEO_EQUIPMENT_80X25_COLOR"; fi
if [ "$CONFIG_VIDEO_MONO" = "y" ]; then VIDEO_EQUIPMENT="BIOS_CFG_VIDEO_EQUIPMENT_MONO"; fi

# --- Generate header ---
{
    echo "#ifndef FREEROS_CONFIG_AUTOGEN_H"
    echo "#define FREEROS_CONFIG_AUTOGEN_H"
    echo ""
    echo "/* Autogenerated by scripts/mkconfig.sh from .config */"
    echo ""

    # Identity
    emit_str "BIOS_CFG_MACHINE_NAME" "${CONFIG_MACHINE_NAME}"
    emit_str "BIOS_CFG_BIOS_BRAND" "${CONFIG_BIOS_BRAND}"
    emit_str "BIOS_CFG_BIOS_STYLE_NAME" "${CONFIG_BIOS_STYLE_NAME}"
    emit_str "BIOS_CFG_WEBSITE" "${CONFIG_WEBSITE}"

    # Hardware
    emit "BIOS_CFG_BASE_MEMORY_KB" "${CONFIG_BASE_MEMORY_KB:-608}"
    emit "BIOS_CFG_HAS_PARADISE_PEGA1A" "$(bool_val "$CONFIG_HAS_PARADISE_PEGA1A")"
    emit "BIOS_CFG_HAS_AMSTRAD_MOUSE" "$(bool_val "$CONFIG_HAS_AMSTRAD_MOUSE")"
    emit "BIOS_CFG_HAS_BATTERY_BACKED_RTC" "$(bool_val "$CONFIG_HAS_BATTERY_BACKED_RTC")"
    emit "BIOS_CFG_HAS_MATH_COPROCESSOR" "$(bool_val "$CONFIG_HAS_MATH_COPROCESSOR")"

    # Ports
    emit "BIOS_CFG_COM1_BASE" "0x$(strip_0x "${CONFIG_COM1_BASE:-03F8}")"
    emit "BIOS_CFG_COM2_BASE" "0x$(strip_0x "${CONFIG_COM2_BASE:-02F8}")"
    emit "BIOS_CFG_LPT1_BASE" "0x$(strip_0x "${CONFIG_LPT1_BASE:-0378}")"
    emit "BIOS_CFG_LPT2_BASE" "0x$(strip_0x "${CONFIG_LPT2_BASE:-03BC}")"

    # Video
    emit "BIOS_CFG_VIDEO_EQUIPMENT" "$VIDEO_EQUIPMENT"
    emit "BIOS_CFG_VIDEO_ATTRIBUTE" "0x$(strip_0x "${CONFIG_VIDEO_ATTRIBUTE:-07}")"
    emit "BIOS_CFG_VIDEO_OPTION_ROM_SCAN_ENABLED" "$(bool_val "$CONFIG_VIDEO_OPTION_ROM_SCAN_ENABLED")"
    emit "BIOS_CFG_OPTION_ROM_SCAN_ENABLED" "$(bool_val "$CONFIG_OPTION_ROM_SCAN_ENABLED")"
    emit "BIOS_CFG_VIDEO_DIRECT_TEXT_INIT" "$(bool_val "$CONFIG_VIDEO_DIRECT_TEXT_INIT")"
    emit "BIOS_CFG_VIDEO_USE_PC1640_SWITCH_BLOCK" "$(bool_val "$CONFIG_VIDEO_USE_PC1640_SWITCH_BLOCK")"
    emit "BIOS_CFG_VIDEO_QUERY_ROM_STATE" "$(bool_val "$CONFIG_VIDEO_QUERY_ROM_STATE")"
    emit "BIOS_CFG_VIDEO_FIXUP_FROM_SWITCH_BLOCK" "$(bool_val "$CONFIG_VIDEO_FIXUP_FROM_SWITCH_BLOCK")"

    # Floppy
    emit "BIOS_CFG_HAS_FLOPPY_CONTROLLER" "$(bool_val "$CONFIG_HAS_FLOPPY_CONTROLLER")"
    emit "BIOS_CFG_FLOPPY_SUPPORT_35_DD" "$(bool_val "$CONFIG_FLOPPY_SUPPORT_35DD")"
    emit "BIOS_CFG_FLOPPY_PROFILE" "BIOS_FLOPPY_PROFILE_CUSTOM"
    emit "BIOS_CFG_FLOPPY_TYPE_A" "$(floppy_type_macro "$FLOPPY_A_TYPE")"
    emit "BIOS_CFG_FLOPPY_TYPE_B" "$(floppy_type_macro "$FLOPPY_B_TYPE")"
    emit "BIOS_CFG_FLOPPY_DRIVES" "$FLOPPY_DRIVES"
    emit "BIOS_CFG_FLOPPY_ENABLE_AH08_COMPAT" "$(bool_val "$CONFIG_FLOPPY_ENABLE_AH08_COMPAT")"

    # IDE
    emit "BIOS_CFG_XTIDE_ENABLED" "$(bool_val "$CONFIG_XTIDE_ENABLED")"
    emit "BIOS_CFG_XTIDE_BASE" "0x$(strip_0x "${CONFIG_XTIDE_BASE:-0300}")"
    emit "BIOS_CFG_XTIDE_BOOT_ENABLED" "$(bool_val "$CONFIG_XTIDE_BOOT_ENABLED")"
    emit "BIOS_CFG_XTIDE_PROBE_MASTER" "$(bool_val "$CONFIG_XTIDE_PROBE_MASTER")"
    emit "BIOS_CFG_XTIDE_PROBE_SLAVE" "$(bool_val "$CONFIG_XTIDE_PROBE_SLAVE")"
    emit "BIOS_CFG_XTIDE_PREFER_LBA" "$(bool_val "$CONFIG_XTIDE_PREFER_LBA")"
    emit "BIOS_CFG_XTIDE_TRANSLATED_HEADS" "${CONFIG_XTIDE_TRANSLATED_HEADS:-255}"
    emit "BIOS_CFG_XTIDE_TRANSLATED_SECTORS" "${CONFIG_XTIDE_TRANSLATED_SECTORS:-63}"
    emit "BIOS_CFG_XTIDE_POLL_LOOPS" "${CONFIG_XTIDE_POLL_LOOPS:-16384}"
    emit "BIOS_CFG_XTIDE_EDD_ENABLED" "$(bool_val "$CONFIG_XTIDE_EDD_ENABLED")"
    emit "BIOS_CFG_XTIDE_EDD_MAX_BLOCKS" "${CONFIG_XTIDE_EDD_MAX_BLOCKS:-127}"

    # RTC
    emit "BIOS_CFG_ROS_RELEASE" "${CONFIG_ROS_RELEASE:-0}"
    emit "BIOS_CFG_ROS_ISSUE" "${CONFIG_ROS_ISSUE:-2}"
    emit "BIOS_CFG_UART_INIT" "0x$(strip_0x "${CONFIG_UART_INIT:-E3}")"
    emit "BIOS_CFG_RTC_DEFAULT_SECONDS" "${CONFIG_RTC_DEFAULT_SECONDS:-0}"
    emit "BIOS_CFG_RTC_DEFAULT_MINUTES" "${CONFIG_RTC_DEFAULT_MINUTES:-0}"
    emit "BIOS_CFG_RTC_DEFAULT_HOURS" "${CONFIG_RTC_DEFAULT_HOURS:-0}"
    emit "BIOS_CFG_RTC_DEFAULT_DAY_OF_MONTH" "${CONFIG_RTC_DEFAULT_DAY_OF_MONTH:-1}"
    emit "BIOS_CFG_RTC_DEFAULT_MONTH" "${CONFIG_RTC_DEFAULT_MONTH:-1}"
    emit "BIOS_CFG_RTC_DEFAULT_YEAR" "${CONFIG_RTC_DEFAULT_YEAR:-88}"
    emit "BIOS_CFG_RTC_DEFAULT_CENTURY" "${CONFIG_RTC_DEFAULT_CENTURY:-19}"

    # POST
    emit "BIOS_CFG_POST_PRETTY_WAIT_PANEL" "$(bool_val "$CONFIG_POST_PRETTY_WAIT_PANEL")"
    emit "BIOS_CFG_POST_SPACE_INVADERS_SOUND" "$(bool_val "$CONFIG_POST_SPACE_INVADERS_SOUND")"

    echo ""
    echo "#endif"
} > "$HEADER"

# --- Generate config.mk ---
{
    echo "# Autogenerated by scripts/mkconfig.sh from .config"

    # Boot floppy image
    BOOT_IMG=""
    if [ "$CONFIG_HAS_FLOPPY_CONTROLLER" = "y" ]; then
        if [ "$FLOPPY_A_TYPE" = "720K" ]; then
            BOOT_IMG="test_media/svdos-720K-disk-1.img"
        elif [ "$FLOPPY_A_TYPE" = "360K" ]; then
            BOOT_IMG="test_media/ibm_dos_330_disk1_360k.img"
        fi
    fi
    echo "CONFIG_BOOT_FLOPPY_IMAGE := $BOOT_IMG"
    echo "CONFIG_FLOPPY_DRIVES := $FLOPPY_DRIVES"

    # Debug defines
    echo "CONFIG_BIOS_DEBUG_DEFS :="
    if [ "$CONFIG_DEBUG_PORT_E9" = "y" ]; then
        echo "CONFIG_BIOS_DEBUG_DEFS += -DBIOS_CFG_DEBUG_PORT_E9=1"
    fi
    if [ "$CONFIG_DEBUG_COM1" = "y" ]; then
        echo "CONFIG_BIOS_DEBUG_DEFS += -DBIOS_CFG_DEBUG_COM1=1"
    fi
    if [ "$CONFIG_DEBUG_VIDEO_STATE" = "y" ]; then
        echo "CONFIG_BIOS_DEBUG_DEFS += -DBIOS_CFG_DEBUG_VIDEO_STATE=1"
    fi
    if [ "$CONFIG_DEBUG_VIDEO_OVERLAY" = "y" ]; then
        echo "CONFIG_BIOS_DEBUG_DEFS += -DBIOS_CFG_DEBUG_VIDEO_OVERLAY=1"
    fi
    if [ "$CONFIG_TRACE_VIDEO_COM1" = "y" ]; then
        echo "CONFIG_BIOS_DEBUG_DEFS += -DBIOS_CFG_TRACE_VIDEO_COM1=1"
    fi
} > "$MAKEFILE"
