#!/usr/bin/env bash

set -eu

REPO_URL="${EIGHTYSIXBOX_REPO_URL:-https://github.com/86Box/86Box.git}"
REPO_DIR="${EIGHTYSIXBOX_REPO:-/tmp/86Box_repo}"
BUILD_DIR="${EIGHTYSIXBOX_BUILD_DIR:-$REPO_DIR/build/pc1640-debug}"
DEBUG_DEFS="${EIGHTYSIXBOX_DEBUG_DEFS:--DENABLE_GDBSTUB_LOG=1 -DENABLE_AMSTRAD_LOG=1 -DENABLE_IO_LOG=1 -DENABLE_VIDEO_LOG=1 -DENABLE_SERIAL_LOG=1 -DENABLE_ISAROM_LOG=1 -DENABLE_SERIAL_PASSTHROUGH_LOG=1}"

if [ ! -d "$REPO_DIR/.git" ]; then
    git clone --depth 1 "$REPO_URL" "$REPO_DIR"
fi

cmake -S "$REPO_DIR" -B "$BUILD_DIR" -G Ninja \
    -DCMAKE_BUILD_TYPE=Debug \
    -DQT=OFF \
    -DOPENAL=ON \
    -DRTMIDI=OFF \
    -DFLUIDSYNTH=OFF \
    -DMUNT=OFF \
    -DDISCORD=OFF \
    -DVNC=OFF \
    -DDYNAREC=OFF \
    -DNEW_DYNAREC=OFF \
    -DGDBSTUB=ON \
    -DDEV_BRANCH=ON \
    -DCMAKE_C_FLAGS_DEBUG="-g -O0 $DEBUG_DEFS" \
    -DCMAKE_CXX_FLAGS_DEBUG="-g -O0 $DEBUG_DEFS"

cmake --build "$BUILD_DIR"

printf '%s\n' "$BUILD_DIR/src/86Box"
