#ifndef NEW_BIOS_CONFIG_H
#define NEW_BIOS_CONFIG_H

/*
 * Central machine configuration for the clean-room PC1640 BIOS.
 *
 * Stock defaults mirror the original PC1640DD firmware profile:
 * - 640 KiB conventional RAM
 * - built-in Paradise PEGA1A video
 * - battery-backed RTC
 * - Amstrad mouse interface
 * - two 360 KiB floppy drives
 *
 * Developer/debug settings are grouped separately at the end so the machine
 * profile can stay stock while bring-up traces remain enabled.
 */

/* Machine identity and core memory. */
#define BIOS_CFG_MACHINE_NAME "Amstrad PC1640DD BIOS"
#define BIOS_CFG_BASE_MEMORY_KB 640
#define BIOS_CFG_EXTENDED_MEMORY_KB 0

/* Integrated machine devices present on the stock board. */
#define BIOS_CFG_HAS_PARADISE_PEGA1A 1
#define BIOS_CFG_HAS_AMSTRAD_MOUSE 1
#define BIOS_CFG_HAS_BATTERY_BACKED_RTC 1
#define BIOS_CFG_HAS_MATH_COPROCESSOR 0

/* Standard PC1640 peripheral port layout. */
#define BIOS_CFG_COM1_BASE 0x03F8
#define BIOS_CFG_COM2_BASE 0x02F8
#define BIOS_CFG_LPT1_BASE 0x0378
#define BIOS_CFG_LPT2_BASE 0x03BC

/* Factory strap defaults. */
#define BIOS_CFG_LANGUAGE BIOS_LANG_ENGLISH
#define BIOS_CFG_LPT_DIP_LATCH LPT1_STATUS_DIP_LATCH
#define BIOS_CFG_LPT1_STATUS ((BIOS_CFG_LANGUAGE & LPT1_STATUS_LANGUAGE_MASK)   \
                              | BIOS_CFG_LPT_DIP_LATCH)

/* Default video state. */
#define BIOS_CFG_VIDEO_EQUIPMENT_EGA_VGA 0x00
#define BIOS_CFG_VIDEO_EQUIPMENT_40X25_COLOR 0x01
#define BIOS_CFG_VIDEO_EQUIPMENT_80X25_COLOR 0x02
#define BIOS_CFG_VIDEO_EQUIPMENT_MONO 0x03
#define BIOS_CFG_VIDEO_MODE_PC1640_COLOR 0x0E
#define BIOS_CFG_VIDEO_MODE_PC1640_MONO 0x0F
#define BIOS_CFG_VIDEO_MODE_DEFAULT BIOS_CFG_VIDEO_MODE_PC1640_COLOR
#define BIOS_CFG_VIDEO_FALLBACK_MODE VIDEO_MODE_80X25_COLOR
#define BIOS_CFG_VIDEO_EQUIPMENT BIOS_CFG_VIDEO_EQUIPMENT_80X25_COLOR
#define BIOS_CFG_VIDEO_COLUMNS 80
#define BIOS_CFG_VIDEO_ROWS 25
#define BIOS_CFG_VIDEO_COLOR_PAGES 4
#define BIOS_CFG_VIDEO_40COL_PAGES 8
#define BIOS_CFG_VIDEO_MONO_PAGES 1
#define BIOS_CFG_VIDEO_ATTRIBUTE 0x07
#define BIOS_CFG_VIDEO_CRTC_PORT 0x03D4
#define BIOS_CFG_VIDEO_SEGMENT BIOS_VIDEO_COLOR_SEGMENT
#define BIOS_CFG_VIDEO_OPTION_ROM_SEGMENT 0xC000
#define BIOS_CFG_VIDEO_OPTION_ROM_SCAN_START 0xC000
#define BIOS_CFG_VIDEO_OPTION_ROM_SCAN_END 0xF000
#define BIOS_CFG_VIDEO_OPTION_ROM_SCAN_STEP 0x0080
#define BIOS_CFG_VIDEO_OPTION_ROM_SCAN_ENABLED 1
#define BIOS_CFG_VIDEO_DIRECT_TEXT_INIT 1
#define BIOS_CFG_VIDEO_USE_PC1640_SWITCH_BLOCK 1
#define BIOS_CFG_VIDEO_QUERY_ROM_STATE 1
#define BIOS_CFG_VIDEO_FIXUP_FROM_SWITCH_BLOCK 1

/* Floppy controller profiles. Stock PC1640DD uses dual 360 KiB drives. */
#define BIOS_FLOPPY_PROFILE_PC1640DD_360K 1
#define BIOS_FLOPPY_PROFILE_TEST_720K 2
#define BIOS_FLOPPY_PROFILE_CUSTOM 3

#define BIOS_CFG_FLOPPY_PROFILE BIOS_FLOPPY_PROFILE_PC1640DD_360K

/*
 * Custom floppy geometry is used only when BIOS_CFG_FLOPPY_PROFILE is set to
 * BIOS_FLOPPY_PROFILE_CUSTOM.
 */
#define BIOS_CFG_FLOPPY_CUSTOM_DRIVES 2
#define BIOS_CFG_FLOPPY_CUSTOM_TYPE_A 0x01
#define BIOS_CFG_FLOPPY_CUSTOM_TYPE_B 0x01
#define BIOS_CFG_FLOPPY_CUSTOM_TRACKS 40
#define BIOS_CFG_FLOPPY_CUSTOM_HEADS 2
#define BIOS_CFG_FLOPPY_CUSTOM_SECTORS 9

#if BIOS_CFG_FLOPPY_PROFILE == BIOS_FLOPPY_PROFILE_PC1640DD_360K
#define BIOS_CFG_FLOPPY_DRIVES 2
#define BIOS_CFG_FLOPPY_TYPE_A 0x01
#define BIOS_CFG_FLOPPY_TYPE_B 0x01
#define BIOS_CFG_FLOPPY_TRACKS 40
#define BIOS_CFG_FLOPPY_HEADS 2
#define BIOS_CFG_FLOPPY_SECTORS 9
#elif BIOS_CFG_FLOPPY_PROFILE == BIOS_FLOPPY_PROFILE_TEST_720K
#define BIOS_CFG_FLOPPY_DRIVES 1
#define BIOS_CFG_FLOPPY_TYPE_A 0x03
#define BIOS_CFG_FLOPPY_TYPE_B 0x00
#define BIOS_CFG_FLOPPY_TRACKS 80
#define BIOS_CFG_FLOPPY_HEADS 2
#define BIOS_CFG_FLOPPY_SECTORS 9
#elif BIOS_CFG_FLOPPY_PROFILE == BIOS_FLOPPY_PROFILE_CUSTOM
#define BIOS_CFG_FLOPPY_DRIVES BIOS_CFG_FLOPPY_CUSTOM_DRIVES
#define BIOS_CFG_FLOPPY_TYPE_A BIOS_CFG_FLOPPY_CUSTOM_TYPE_A
#define BIOS_CFG_FLOPPY_TYPE_B BIOS_CFG_FLOPPY_CUSTOM_TYPE_B
#define BIOS_CFG_FLOPPY_TRACKS BIOS_CFG_FLOPPY_CUSTOM_TRACKS
#define BIOS_CFG_FLOPPY_HEADS BIOS_CFG_FLOPPY_CUSTOM_HEADS
#define BIOS_CFG_FLOPPY_SECTORS BIOS_CFG_FLOPPY_CUSTOM_SECTORS
#else
#error Unsupported BIOS_CFG_FLOPPY_PROFILE value
#endif

#define BIOS_CFG_FLOPPY_SECTOR_SIZE 512
#define BIOS_CFG_FLOPPY_ENABLE_AH08_COMPAT 1
#define BIOS_CFG_FLOPPY_RATE 0x02
#define BIOS_CFG_FLOPPY_SPEC1 0xDF
#define BIOS_CFG_FLOPPY_SPEC2 0x02
#define BIOS_CFG_FLOPPY_GAP 0x2A

/* RTC power-on defaults. */
#define BIOS_CFG_RTC_DEFAULT_SECONDS 0
#define BIOS_CFG_RTC_DEFAULT_MINUTES 0
#define BIOS_CFG_RTC_DEFAULT_HOURS 0
#define BIOS_CFG_RTC_DEFAULT_DAY_OF_MONTH 1
#define BIOS_CFG_RTC_DEFAULT_MONTH 1
#define BIOS_CFG_RTC_DEFAULT_YEAR 88
#define BIOS_CFG_RTC_DEFAULT_CENTURY 19

/* Developer/debug routing. These do not describe stock hardware. */
#define BIOS_CFG_DEBUG_PORT_E9 1
#define BIOS_CFG_DEBUG_COM1 1
#define BIOS_CFG_DEBUG_VIDEO_STATE 1
#define BIOS_CFG_DEBUG_VIDEO_OVERLAY 1

/* Cosmetic POST options. */
#define BIOS_CFG_POST_PRETTY_WAIT_PANEL 1

#endif
