#ifndef NEW_BIOS_CONFIG_H
#define NEW_BIOS_CONFIG_H

/*
 * Central machine configuration for the clean-room PC1640 BIOS.
 *
 * Stock defaults mirror the original PC1640DD firmware profile:
 * - 640 KiB conventional RAM
 * - built-in Paradise PEGA1A video
 * - battery-backed RTC
 * - Amstrad mouse interface
 * - two 360 KiB floppy drives
 *
 * Developer/debug settings are grouped separately at the end so the machine
 * profile can stay stock while bring-up traces remain enabled.
 */

/* Machine identity and core memory. */
#define BIOS_CFG_MACHINE_NAME "FreeRos PC1640 Compatible BIOS"
#define BIOS_CFG_BIOS_BRAND "FreeRos"
#define BIOS_CFG_BIOS_STYLE_NAME "PC1640-Compatible System BIOS"
#define BIOS_CFG_WEBSITE "www.xt-emporium.com"
#define BIOS_CFG_BASE_MEMORY_KB 608
/* Integrated machine devices present on the stock board. */
#define BIOS_CFG_HAS_PARADISE_PEGA1A 1
#define BIOS_CFG_HAS_AMSTRAD_MOUSE 1
#define BIOS_CFG_HAS_BATTERY_BACKED_RTC 1
#define BIOS_CFG_HAS_MATH_COPROCESSOR 0

/* Standard PC1640 peripheral port layout. */
#define BIOS_CFG_COM1_BASE 0x03F8
#define BIOS_CFG_COM2_BASE 0x02F8
#define BIOS_CFG_LPT1_BASE 0x0378
#define BIOS_CFG_LPT2_BASE 0x03BC

/* Factory strap defaults. */
#define BIOS_CFG_LANGUAGE BIOS_LANG_ENGLISH
#define BIOS_CFG_LPT_DIP_LATCH LPT1_STATUS_DIP_LATCH
#define BIOS_CFG_LPT1_STATUS ((BIOS_CFG_LANGUAGE & LPT1_STATUS_LANGUAGE_MASK)   \
                              | BIOS_CFG_LPT_DIP_LATCH)

/* Default video state. */
#define BIOS_CFG_VIDEO_EQUIPMENT_EGA_ADAPTER 0x00
#define BIOS_CFG_VIDEO_EQUIPMENT_40X25_COLOR 0x01
#define BIOS_CFG_VIDEO_EQUIPMENT_80X25_COLOR 0x02
#define BIOS_CFG_VIDEO_EQUIPMENT_MONO 0x03
#define BIOS_CFG_VIDEO_MODE_PC1640_COLOR 0x0E
#define BIOS_CFG_VIDEO_MODE_PC1640_MONO 0x0F
#define BIOS_CFG_VIDEO_MODE_DEFAULT BIOS_CFG_VIDEO_MODE_PC1640_COLOR
#define BIOS_CFG_VIDEO_FALLBACK_MODE VIDEO_MODE_80X25_COLOR
#define BIOS_CFG_VIDEO_EQUIPMENT BIOS_CFG_VIDEO_EQUIPMENT_80X25_COLOR
#define BIOS_CFG_VIDEO_COLUMNS 80
#define BIOS_CFG_VIDEO_ROWS 25
#define BIOS_CFG_VIDEO_MAX_ROWS 43
#define BIOS_CFG_VIDEO_COLOR_PAGES 4
#define BIOS_CFG_VIDEO_40COL_PAGES 8
#define BIOS_CFG_VIDEO_MONO_PAGES 1
#define BIOS_CFG_VIDEO_ATTRIBUTE 0x07
#define BIOS_CFG_VIDEO_CRTC_PORT 0x03D4
#define BIOS_CFG_VIDEO_SEGMENT BIOS_VIDEO_COLOR_SEGMENT
#define BIOS_CFG_VIDEO_OPTION_ROM_SEGMENT 0xC000
#define BIOS_CFG_VIDEO_OPTION_ROM_SCAN_START 0xC000
#define BIOS_CFG_VIDEO_OPTION_ROM_SCAN_END 0xC800
#define BIOS_CFG_VIDEO_OPTION_ROM_SCAN_STEP 0x0080
#define BIOS_CFG_VIDEO_OPTION_ROM_SCAN_ENABLED 1
#define BIOS_CFG_OPTION_ROM_SCAN_START 0xC800
#define BIOS_CFG_OPTION_ROM_SCAN_END 0xF000
#define BIOS_CFG_OPTION_ROM_SCAN_STEP 0x0080
#define BIOS_CFG_OPTION_ROM_SCAN_ENABLED 1
#define BIOS_CFG_VIDEO_DIRECT_TEXT_INIT 1
#define BIOS_CFG_VIDEO_USE_PC1640_SWITCH_BLOCK 1
#define BIOS_CFG_VIDEO_QUERY_ROM_STATE 1
#define BIOS_CFG_VIDEO_FIXUP_FROM_SWITCH_BLOCK 1

/* Floppy controller profiles. Stock PC1640DD uses dual 360 KiB drives. */
#define BIOS_CFG_HAS_FLOPPY_CONTROLLER 0
#define BIOS_FLOPPY_TYPE_NONE 0x00
#define BIOS_FLOPPY_TYPE_360K_525DD 0x01
#define BIOS_FLOPPY_TYPE_720K_35DD 0x03

#define BIOS_FLOPPY_PROFILE_PC1640DD_360K 1
#define BIOS_FLOPPY_PROFILE_TEST_720K 2
#define BIOS_FLOPPY_PROFILE_CUSTOM 3

#define BIOS_CFG_FLOPPY_PROFILE BIOS_FLOPPY_PROFILE_PC1640DD_360K
#define BIOS_CFG_FLOPPY_SUPPORT_35_DD 1

/*
 * Custom floppy geometry is used only when BIOS_CFG_FLOPPY_PROFILE is set to
 * BIOS_FLOPPY_PROFILE_CUSTOM.
 */
#define BIOS_CFG_FLOPPY_CUSTOM_DRIVES 2
#define BIOS_CFG_FLOPPY_CUSTOM_TYPE_A BIOS_FLOPPY_TYPE_360K_525DD
#define BIOS_CFG_FLOPPY_CUSTOM_TYPE_B BIOS_FLOPPY_TYPE_360K_525DD
#define BIOS_CFG_FLOPPY_CUSTOM_TRACKS 40
#define BIOS_CFG_FLOPPY_CUSTOM_HEADS 2
#define BIOS_CFG_FLOPPY_CUSTOM_SECTORS 9

#if BIOS_CFG_FLOPPY_PROFILE == BIOS_FLOPPY_PROFILE_PC1640DD_360K
#define BIOS_CFG_FLOPPY_DRIVES 2
#define BIOS_CFG_FLOPPY_TYPE_A BIOS_FLOPPY_TYPE_360K_525DD
#define BIOS_CFG_FLOPPY_TYPE_B BIOS_FLOPPY_TYPE_360K_525DD
#define BIOS_CFG_FLOPPY_TRACKS 40
#define BIOS_CFG_FLOPPY_HEADS 2
#define BIOS_CFG_FLOPPY_SECTORS 9
#elif BIOS_CFG_FLOPPY_PROFILE == BIOS_FLOPPY_PROFILE_TEST_720K
#define BIOS_CFG_FLOPPY_DRIVES 1
#define BIOS_CFG_FLOPPY_TYPE_A BIOS_FLOPPY_TYPE_720K_35DD
#define BIOS_CFG_FLOPPY_TYPE_B BIOS_FLOPPY_TYPE_NONE
#define BIOS_CFG_FLOPPY_TRACKS 80
#define BIOS_CFG_FLOPPY_HEADS 2
#define BIOS_CFG_FLOPPY_SECTORS 9
#elif BIOS_CFG_FLOPPY_PROFILE == BIOS_FLOPPY_PROFILE_CUSTOM
#define BIOS_CFG_FLOPPY_DRIVES BIOS_CFG_FLOPPY_CUSTOM_DRIVES
#define BIOS_CFG_FLOPPY_TYPE_A BIOS_CFG_FLOPPY_CUSTOM_TYPE_A
#define BIOS_CFG_FLOPPY_TYPE_B BIOS_CFG_FLOPPY_CUSTOM_TYPE_B
#define BIOS_CFG_FLOPPY_TRACKS BIOS_CFG_FLOPPY_CUSTOM_TRACKS
#define BIOS_CFG_FLOPPY_HEADS BIOS_CFG_FLOPPY_CUSTOM_HEADS
#define BIOS_CFG_FLOPPY_SECTORS BIOS_CFG_FLOPPY_CUSTOM_SECTORS
#else
#error Unsupported BIOS_CFG_FLOPPY_PROFILE value
#endif

#define BIOS_CFG_FLOPPY_SECTOR_SIZE 512
#define BIOS_CFG_FLOPPY_ENABLE_AH08_COMPAT 1
#define BIOS_CFG_FLOPPY_RATE 0x02
#define BIOS_CFG_FLOPPY_SPEC1 0xDF
#define BIOS_CFG_FLOPPY_SPEC2 0x02
#define BIOS_CFG_FLOPPY_GAP 0x2A

/* Optional XTIDE-compatible 8-bit ISA IDE support. */
#define BIOS_CFG_XTIDE_ENABLED 1
#define BIOS_CFG_XTIDE_BASE 0x0300
#define BIOS_CFG_XTIDE_BOOT_ENABLED 1
#define BIOS_CFG_XTIDE_PROBE_MASTER 1
#define BIOS_CFG_XTIDE_PROBE_SLAVE 1
#define BIOS_CFG_XTIDE_PREFER_LBA 1
#define BIOS_CFG_XTIDE_TRANSLATED_HEADS 255
#define BIOS_CFG_XTIDE_TRANSLATED_SECTORS 63
#define BIOS_CFG_XTIDE_POLL_LOOPS 16384
#define BIOS_CFG_XTIDE_EDD_ENABLED 1
#define BIOS_CFG_XTIDE_EDD_MAX_BLOCKS 127

/* RTC power-on defaults. */
#define BIOS_CFG_ROS_RELEASE 0
#define BIOS_CFG_ROS_ISSUE 2
#define BIOS_CFG_UART_INIT 0xE3
#define BIOS_CFG_RTC_DEFAULT_SECONDS 0
#define BIOS_CFG_RTC_DEFAULT_MINUTES 0
#define BIOS_CFG_RTC_DEFAULT_HOURS 0
#define BIOS_CFG_RTC_DEFAULT_DAY_OF_MONTH 1
#define BIOS_CFG_RTC_DEFAULT_MONTH 1
#define BIOS_CFG_RTC_DEFAULT_YEAR 26
#define BIOS_CFG_RTC_DEFAULT_CENTURY 21

/* Developer/debug routing. These do not describe stock hardware. */
#ifndef BIOS_CFG_DEBUG_PORT_E9
#define BIOS_CFG_DEBUG_PORT_E9 0
#endif
#ifndef BIOS_CFG_DEBUG_COM1
#define BIOS_CFG_DEBUG_COM1 0
#endif
#ifndef BIOS_CFG_DEBUG_VIDEO_STATE
#define BIOS_CFG_DEBUG_VIDEO_STATE 0
#endif
#ifndef BIOS_CFG_DEBUG_VIDEO_OVERLAY
#define BIOS_CFG_DEBUG_VIDEO_OVERLAY 0
#endif
#ifndef BIOS_CFG_TRACE_VIDEO_COM1
#define BIOS_CFG_TRACE_VIDEO_COM1 0
#endif

/* Cosmetic POST options. */
#define BIOS_CFG_POST_PRETTY_WAIT_PANEL 1
#define BIOS_CFG_POST_SPACE_INVADERS_SOUND 0

#include "config_autogen.h"

#if (BIOS_CFG_FLOPPY_TYPE_A != BIOS_FLOPPY_TYPE_NONE                          \
     && BIOS_CFG_FLOPPY_TYPE_A != BIOS_FLOPPY_TYPE_360K_525DD                \
     && BIOS_CFG_FLOPPY_TYPE_A != BIOS_FLOPPY_TYPE_720K_35DD)                \
  || (BIOS_CFG_FLOPPY_TYPE_B != BIOS_FLOPPY_TYPE_NONE                        \
      && BIOS_CFG_FLOPPY_TYPE_B != BIOS_FLOPPY_TYPE_360K_525DD               \
      && BIOS_CFG_FLOPPY_TYPE_B != BIOS_FLOPPY_TYPE_720K_35DD)
#error Unsupported floppy drive type selected
#endif

#if !BIOS_CFG_FLOPPY_SUPPORT_35_DD                                            \
  && (BIOS_CFG_FLOPPY_TYPE_A == BIOS_FLOPPY_TYPE_720K_35DD                    \
      || BIOS_CFG_FLOPPY_TYPE_B == BIOS_FLOPPY_TYPE_720K_35DD)
#error 720K 3.5in support is disabled but a 720K drive is configured
#endif

#if !BIOS_CFG_HAS_FLOPPY_CONTROLLER                                            \
  && (BIOS_CFG_FLOPPY_TYPE_A != BIOS_FLOPPY_TYPE_NONE                         \
      || BIOS_CFG_FLOPPY_TYPE_B != BIOS_FLOPPY_TYPE_NONE                      \
      || BIOS_CFG_FLOPPY_DRIVES != 0)
#error Floppy controller is disabled but floppy drives are still configured
#endif

#if BIOS_CFG_FLOPPY_TYPE_A == BIOS_FLOPPY_TYPE_NONE                           \
  && BIOS_CFG_FLOPPY_TYPE_B != BIOS_FLOPPY_TYPE_NONE
#error Drive B cannot be present when drive A is not installed
#endif

#if BIOS_CFG_FLOPPY_DRIVES != (((BIOS_CFG_FLOPPY_TYPE_A != BIOS_FLOPPY_TYPE_NONE) ? 1 : 0) \
                               + ((BIOS_CFG_FLOPPY_TYPE_B != BIOS_FLOPPY_TYPE_NONE) ? 1 : 0))
#error BIOS_CFG_FLOPPY_DRIVES does not match the configured drive types
#endif

#if BIOS_CFG_XTIDE_BASE < 0x0200 || BIOS_CFG_XTIDE_BASE > 0x03F0            \
  || (BIOS_CFG_XTIDE_BASE & 0x000F)
#error BIOS_CFG_XTIDE_BASE must be a 16-byte-aligned XTIDE I/O base
#endif

#if BIOS_CFG_XTIDE_TRANSLATED_HEADS < 1 || BIOS_CFG_XTIDE_TRANSLATED_HEADS > 255
#error BIOS_CFG_XTIDE_TRANSLATED_HEADS must be in the range 1..255
#endif

#if BIOS_CFG_XTIDE_TRANSLATED_SECTORS < 1                               \
  || BIOS_CFG_XTIDE_TRANSLATED_SECTORS > 63
#error BIOS_CFG_XTIDE_TRANSLATED_SECTORS must be in the range 1..63
#endif

#if BIOS_CFG_XTIDE_POLL_LOOPS < 256
#error BIOS_CFG_XTIDE_POLL_LOOPS must be at least 256
#endif

#if BIOS_CFG_XTIDE_EDD_MAX_BLOCKS < 1 || BIOS_CFG_XTIDE_EDD_MAX_BLOCKS > 127
#error BIOS_CFG_XTIDE_EDD_MAX_BLOCKS must be in the range 1..127
#endif

#endif
